# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GS6Pq0Zv8XyWoYDbFOhJYCZXgU-90934

Integrantes: Anna Luiza 563388,
Karen (**representante**) 562733,
Thalita 566381.

**Global Solution:** *Engajamento da população nos Grandes Desastres*
"""

# Inicializando GS

print("Bem-vindo(a) ao sistema de monitoramento diante os desastres naturais.")

# Lista principal que irá armazenar os desastres
# Cada desastre será representado por uma lista com seus dados

desastres = []

# Solicita a quantidade de desastres
qtd_desastres = int(input("Informe a quantidade de desastres a serem registrados: "))

# Cadastro dos dados de cada desastre
for i in range(qtd_desastres):
    print(f"\nCadastro do desastre {i + 1}")

    tipo = input("Tipo de desastre (ex: incêndio, enchente, etc.): ")
    pais = input("País: ")
    cidade = input("Cidade: ")
    bairro = input("Bairro: ")
    rua = input("Rua: ")

    # Loop para garantir que a soma das categorias bate com o total
    while True:
        total = int(input("Quantidade total de pessoas afetadas: "))
        qtd_criancas = int(input("Quantidade de crianças: "))
        qtd_adultos = int(input("Quantidade de adultos: "))
        qtd_idosos = int(input("Quantidade de idosos: "))
        qtd_mob_red = int(input("Quantidade de pessoas com mobilidade reduzida: "))
        qtd_feridos = int(input("Quantidade de feridos: "))

        # Calcula a soma das categorias
        soma_categorias = qtd_criancas + qtd_adultos + qtd_idosos + qtd_mob_red + qtd_feridos

        # Validação
        if soma_categorias == total:
            break  # Dados corretos, sai do while
        else:
            print("\nA soma das categorias NÃO corresponde ao total de pessoas afetadas.")
            print("Por favor, digite os dados novamente.\n")

    # Cria uma lista com os dados do desastre
    desastre = [
        tipo,
        pais,
        cidade,
        bairro,
        rua,
        total,
        qtd_criancas,
        qtd_adultos,
        qtd_idosos,
        qtd_mob_red,
        qtd_feridos
    ]

    # Adiciona o desastre na lista principal
    desastres.append(desastre)

# Processamento dos dados

# Soma por categorias gerais
qtd_criancas = sum(desastre[6] for desastre in desastres)
qtd_adultos = sum(desastre[7] for desastre in desastres)
qtd_idosos = sum(desastre[8] for desastre in desastres)
qtd_mob_red = sum(desastre[9] for desastre in desastres)
qtd_feridos = sum(desastre[10] for desastre in desastres)

# Lista para armazenar os totais de afetados de cada desastre
totais_afetados = []

# Percorre a lista de desastres e extrai os totais de afetados
for desastre in desastres:
    totais_afetados.append(desastre[5])

# Maior número de afetados
maior_afetados = max(totais_afetados)

# Índice do desastre com o maior número de afetados
indice_maior = totais_afetados.index(maior_afetados)

# Cálculo do total geral de pessoas afetadas
total_geral = sum(totais_afetados)

# Determinação das categorias mais afetadas
categorias = {
    "crianças": qtd_criancas,
    "adultos": qtd_adultos,
    "idosos": qtd_idosos,
    "mobilidade reduzida": qtd_mob_red,
    "feridos": qtd_feridos
}

# Encontra o valor máximo entre as categorias
max_valor = max(categorias.values())

# Lista todas as categorias que possuem o valor máximo
categorias_mais_afetadas = [categoria for categoria, valor in categorias.items() if valor == max_valor]

# Exibição dos dados

print("\n\nDados dos Desastres Registrados")
print(f"\nQuantidade de desastres registrados: {qtd_desastres}")
print(f"\nResumo de pessoas afetadas por categoria: \nCrianças: {qtd_criancas} | Adultos: {qtd_adultos} | Idosos: {qtd_idosos} | Mobilidade reduzida: {qtd_mob_red} | Feridos: {qtd_feridos}")


print(f"\nTotal geral de pessoas afetadas: {total_geral}")
print("Categoria(s) mais afetada(s):")
for categoria in categorias_mais_afetadas:
    print(f"] {categoria} ({max_valor} pessoas)")

# Exibe o desastre com maior número de afetados

print("\n\nDesastre com MAIOR número de afetados")
maior_desastre = desastres[indice_maior]
print(f"Tipo: {maior_desastre[0]}")
print(f"Localização: {maior_desastre[4]}, {maior_desastre[3]}, {maior_desastre[2]}, {maior_desastre[1]}")
print(f"Total de afetados: {maior_desastre[5]}")